/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.io.File;
import javazoom.jlgui.basicplayer.BasicPlayer;
import javazoom.jlgui.basicplayer.BasicPlayerException;

/**
 *
 * @author PC 2
 */
public class Principal extends javax.swing.JFrame {
    
    private BasicPlayer sonido;
    
    
    public Principal() {
        initComponents();
        this.setSize(357, 532);
        this.setLocationRelativeTo(null);
        
        sonido = new BasicPlayer();
        abrirFichero("Music_PKMN"+File.separator+"Pokémon Rojo FuegoVerde Hoja OST - 02 - Tema Principal.mp3");
        reproducir();
    }
    
    
    public void reproducir(){
        try{
            sonido.play();
        }catch(BasicPlayerException e){
            System.out.println(e);
        }
    }
    
    public void abrirFichero(String archivo){
        try{
            sonido.open(new File(archivo));
        }catch(BasicPlayerException e){
            System.out.println(e);
        }
    }
    
    public void mostrarVentana(){
        Seleccion_PKMN sp = new Seleccion_PKMN();
        sp.setVisible(true);
        try {
            this.sonido.stop();
        } catch (BasicPlayerException e) {
            System.out.println(e);
        }
        this.dispose();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Iniciar = new javax.swing.JButton();
        Iniciar_2 = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        Iniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_PKMN/Letras_Intro.png"))); // NOI18N
        Iniciar.setBorderPainted(false);
        Iniciar.setContentAreaFilled(false);
        Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarActionPerformed(evt);
            }
        });
        getContentPane().add(Iniciar);
        Iniciar.setBounds(60, 100, 240, 80);

        Iniciar_2.setBorderPainted(false);
        Iniciar_2.setContentAreaFilled(false);
        Iniciar_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Iniciar_2ActionPerformed(evt);
            }
        });
        getContentPane().add(Iniciar_2);
        Iniciar_2.setBounds(0, -1, 350, 510);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_PKMN/Intro.gif"))); // NOI18N
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 351, 504);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarActionPerformed
        mostrarVentana();
    }//GEN-LAST:event_IniciarActionPerformed

    private void Iniciar_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Iniciar_2ActionPerformed
        mostrarVentana();
    }//GEN-LAST:event_Iniciar_2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton Iniciar;
    private javax.swing.JButton Iniciar_2;
    // End of variables declaration//GEN-END:variables
}
