/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.io.File;
import javax.swing.ImageIcon;
import javazoom.jlgui.basicplayer.BasicPlayer;
import javazoom.jlgui.basicplayer.BasicPlayerException;

/**
 *
 * @author PC 2
 */
public class Seleccion_PKMN extends javax.swing.JFrame {

    ImageIcon imageIcon = new ImageIcon();
    private BasicPlayer sonido;
    
    public Seleccion_PKMN() {
        initComponents();
        this.setSize(735, 485);
        this.setLocationRelativeTo(null);
        
        sonido = new BasicPlayer();
        abrirFichero("Music_PKMN"+File.separator+"Pokémon Rojo FuegoVerde Hoja OST - 03 - Instrucciones.mp3");
        reproducir();
        
    }
    
    
    public void reproducir(){
        try{
            sonido.play();
        }catch(BasicPlayerException e){
            System.out.println(e);
        }
    }
    
    public void abrirFichero(String archivo){
        try{
            sonido.open(new File(archivo));
        }catch(BasicPlayerException e){
            System.out.println(e);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Charizard = new javax.swing.JButton();
        Breloom = new javax.swing.JButton();
        Gengar = new javax.swing.JButton();
        Ampharos = new javax.swing.JButton();
        Aerodactyl = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Charizard.setBorderPainted(false);
        Charizard.setContentAreaFilled(false);
        Charizard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CharizardActionPerformed(evt);
            }
        });
        getContentPane().add(Charizard);
        Charizard.setBounds(160, 80, 140, 140);

        Breloom.setBorderPainted(false);
        Breloom.setContentAreaFilled(false);
        Breloom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BreloomActionPerformed(evt);
            }
        });
        getContentPane().add(Breloom);
        Breloom.setBounds(160, 290, 120, 120);

        Gengar.setToolTipText("");
        Gengar.setBorderPainted(false);
        Gengar.setContentAreaFilled(false);
        Gengar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GengarActionPerformed(evt);
            }
        });
        getContentPane().add(Gengar);
        Gengar.setBounds(357, 307, 130, 110);

        Ampharos.setBorderPainted(false);
        Ampharos.setContentAreaFilled(false);
        Ampharos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmpharosActionPerformed(evt);
            }
        });
        getContentPane().add(Ampharos);
        Ampharos.setBounds(550, 270, 110, 120);

        Aerodactyl.setBorderPainted(false);
        Aerodactyl.setContentAreaFilled(false);
        Aerodactyl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AerodactylActionPerformed(evt);
            }
        });
        getContentPane().add(Aerodactyl);
        Aerodactyl.setBounds(390, 80, 170, 150);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_PKMN/Letras_Seleccion.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 10, 450, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_PKMN/Charizard.gif"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 80, 140, 140);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_PKMN/Aerodactyl.gif"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(390, 80, 170, 150);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_PKMN/Breloom.gif"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 300, 70, 100);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_PKMN/Gengar.gif"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(380, 310, 90, 100);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_PKMN/Ampharos.gif"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(570, 270, 80, 110);

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img_PKMN/Fondo1.png"))); // NOI18N
        getContentPane().add(Fondo);
        Fondo.setBounds(0, 0, 720, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BreloomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BreloomActionPerformed
        Batalla_Breloom bb = new Batalla_Breloom();
        bb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BreloomActionPerformed

    private void CharizardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CharizardActionPerformed
        Batalla_Charizard bc = new Batalla_Charizard();
        bc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CharizardActionPerformed

    private void GengarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GengarActionPerformed
        Batalla_Gengar bg = new Batalla_Gengar();
        bg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_GengarActionPerformed

    private void AerodactylActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AerodactylActionPerformed
        Batalla_Aerodactyl bae = new Batalla_Aerodactyl();
        bae.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AerodactylActionPerformed

    private void AmpharosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmpharosActionPerformed
        Batalla_Ampharos bam = new Batalla_Ampharos();
        bam.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AmpharosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seleccion_PKMN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seleccion_PKMN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seleccion_PKMN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seleccion_PKMN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seleccion_PKMN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aerodactyl;
    private javax.swing.JButton Ampharos;
    private javax.swing.JButton Breloom;
    private javax.swing.JButton Charizard;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton Gengar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
